# Generated by Django 5.2.9 on 2026-01-05 07:24

from django.db import migrations


def create_predefined_categories(apps, schema_editor):
    Category = apps.get_model('categories', 'Category')

    predefined_categories = [
        'Artificial Intelligence',
        'Programming',
        'Graphic Design',
        'Other'
    ]

    for category_name in predefined_categories:
        Category.objects.get_or_create(name=category_name)


def remove_predefined_categories(apps, schema_editor):
    Category = apps.get_model('categories', 'Category')

    predefined_categories = [
        'Artificial Intelligence',
        'Programming',
        'Graphic Design',
        'Other'
    ]

    Category.objects.filter(name__in=predefined_categories).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_predefined_categories, remove_predefined_categories),
    ]
